### ISSUE TITLE
Error launch

### ISSUE THREAD

**Issue by DIMANRUS** [Qonfused/OSX-Hyper-V#20]
Hello. I created everything step by step using scripts in Readme, but this problem occurred when starting. What could be the reason for this? I have attached a file with logs below.
![image](https://github.com/user-attachments/assets/9b026995-48d5-4796-b487-680b5cff1a7e)
[opencore-2024-10-26-210258.txt](https://github.com/user-attachments/files/17531609/opencore-2024-10-26-210258.txt)

**Comment by Qonfused** [comment]
This is an early kernel panic caused by an unsupported CPUID. 11th gen (Rocket Lake) CPUs aren't natively supported so you'll need to spoof as 10th gen (Comet Lake).
```
00:021 00:001 OCCPU: Found 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
00:023 00:001 OCCPU: Signature 806C1 Stepping 1 Model 8C Family 6 Type 0 ExtModel 8 ExtFamily 0 uCode FFFFFFFF CPUID MAX (1B/80000008)
```

You'll want to add the below entries under the [Kernel > Emulate](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#kernel---emulate) section of your config.plist (or add this to the config.yml file and re-build this repo):
```yaml
Kernel:
  Emulate:
    Cpuid1Data: Data | EB060900 00000000 00000000 00000000
    Cpuid1Mask: Data | FFFFFFFF 00000000 00000000 00000000
```

Also see https://github.com/Qonfused/OSX-Hyper-V/issues/2 as this is the same case for Alder Lake (12th gen) and Raptor Lake (13th/14th gen) CPUs.

**Comment by DIMANRUS** [comment]
Thank you very much for your reply. I have moved further, but I am stuck on an error, as I understand it, not displaying the GUI for selecting a language. I have seen this in other issues, but I have an Intel processor. Any thoughts on why it does not give? I tried UEFI from another repository, the installer starts there, but after that the system does not want to start.
![image](https://github.com/user-attachments/assets/086b40b5-9c5b-4b1c-8122-0763f773cc25)

**Comment by Qonfused** [comment]
Interesting. I haven't been able to reproduce that on AMD so I wasn't sure if it was some kind of misconfiguration on the user's part. In this case, the only configuration needed for 11th gen was the CPUID spoof.

Can you try with `55060A00` instead of `EB060900` for the first CPUID bit?
```yaml
Kernel:
  Emulate:
    Cpuid1Data: Data | 55060A00 00000000 00000000 00000000
```

This corresponds to a Comet-Lake CPUID instead of a Coffee-Lake CPUID (which use the same driver). I'm curious if there is any CPUID-related startup behavior behind this issue.

**Comment by DIMANRUS** [comment]
Thanks for the answer. I tried replacing it, but the error remained. I attached the log and the configuration I use. The log still shows the name of my 11th generation processor when I start it, is that how it should be? Maybe I wrote the lines you mentioned above in the wrong place?
[opencore-2024-10-27-233153.txt](https://github.com/user-attachments/files/17535381/opencore-2024-10-27-233153.txt)
[config.zip](https://github.com/user-attachments/files/17535384/config.zip)

**Comment by DIMANRUS** [comment]
Thanks for the answer. I tried replacing it, but the error remained. I attached the log and the configuration I use. The log still shows the name of my 11th generation processor when I start it, is that how it should be? Maybe I wrote the lines you mentioned above in the wrong place?
[opencore-2024-10-27-233153.txt](https://github.com/user-attachments/files/17535381/opencore-2024-10-27-233153.txt)
[config.zip](https://github.com/user-attachments/files/17535384/config.zip)

**Comment by Qonfused** [comment]
The OpenCore log will always display the CPU information correctly even if you spoof it; the CPUID spoof just tricks macOS into treating the CPU as supported.

This gets logged very early on before later applying the CPUID patch:
```
00:031 00:002 OCCPU: Found 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
00:034 00:002 OCCPU: Signature 806C1 Stepping 1 Model 8C Family 6 Type 0 ExtModel 8 ExtFamily 0 uCode FFFFFFFF CPUID MAX (1B/80000008)
...
18:415 00:002 OCAK: [OK] Patch success CPUID release
```

I also just tested the i9-11900KF on the same configuration but still haven't figured out how to reproduce this issue. 

I'm curious if this issue is flaky and somehow performance related since the i7-11370H shouldn't face any compatibility issues. Just to make sure there isn't any blocking virtual disk I/O or VMQ issues, I'd [disable checkpoints](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/enable-or-disable-checkpoints-in-hyper-v) for your VM:

```powershell
Set-VM -Name <name> -AutomaticCheckpointsEnabled $false
```

May be worth re-creating the VM in Hyper-V with this setting disabled just to verify.

**Comment by DIMANRUS** [comment]
I always disable checkpoints, so without them it is also a mistake.

**Comment by DIMANRUS** [comment]
I have a GUI running with this EFI. I opened the EFI disk and replaced your EFI with this one.
[EFI.zip](https://github.com/user-attachments/files/17537607/EFI.zip)

**Comment by Qonfused** [comment]
These were the only functional changes I noticed:
```yaml
Kernel:
  Emulate:
    DummyPowerManagement:  Boolean | false
PlatformInfo:
  Generic:
    SystemProductName:     String  | "MacBookAir8,1"
```
Omitted are changes applied for legacy/32-bit systems that are present in both.

Curious why the SMBIOS is set to the MacBookAir8,1 since this was just dropped in Sequoia. It's not generally a good fit for this CPU (and most desktop and laptop CPUs) as it's based on an Amber-Lake Y model laptop.

If it doesn't make a difference it might just be a flaky issue.

**Comment by DIMANRUS** [comment]
Thanks for the answer. I tried with and without it on the i3-12100 processor, the problem is the same in both cases. Later I will try again on the i7-11370H

**Comment by Qonfused** [comment]
Those VirtualSMC plugins shouldn't affect boot as far as I'm aware.

**Comment by Qonfused** [comment]
Not sure if the BiosVideo.efi driver will do anything without `ReconnectGraphicsOnConnect` enabled:

> CSM video driver implementing graphics output protocol based on VESA and legacy BIOS interfaces. Used for UEFI firmware with fragile GOP support (e.g. low resolution). Requires ReconnectGraphicsOnConnect. Included in OpenDuet out of the box.

I'd try booting with this disabled just to verify. Maybe there aren't any graphics drivers connected when this driver gets loaded?

**Comment by DIMANRUS** [comment]
After the installation has started on the screen with the apple, then with the current kext and drivers it turns into the screen below
![image](https://github.com/user-attachments/assets/74c53864-eb0f-44f6-a21f-bb354e41c6e3)
But if I turn off the machine, remove what I added, that is, return the plist to your configuration, then the installation goes through and starts.
![image](https://github.com/user-attachments/assets/dc988448-7d5a-4439-b1fe-b12f4de060cd)
