### ISSUE TITLE
Unable to start VM

### ISSUE THREAD

**Issue by owaingeek** [Qonfused/OSX-Hyper-V#21]
When attempting to start the VM, the screen just flickers the Hyper-V logo and turns off. Screen cap is below:
https://drive.google.com/file/d/1bTqvy4Bg9l8WsxFIvlfjzW9D6548GgEv/view?usp=sharing

**Comment by Qonfused** [comment]
What virtual disks do you have connected to the VM? I'd double check that boot order under the hardware section for 'SCSI Controller' prioritizes the EFI virtual disk:
> - Navigate to 'SCSI Controller' and add a new hard drive for your EFI VHDX (and installer VHDX if applicable).
> - You'll need to attach your EFI VHDX with a location value of `0` and change the location value for your main virtual hard disk to a different value (e.g. `1` or `2`). This is to ensure that the EFI disk is the first disk in the boot order.

If you have your `com.apple.recovery.boot` macOS base image on the EFI virtual disk, that is also fine.

**Comment by owaingeek** [comment]
Hiya, 
I did have my EFI on 0 and my main virtual hard disk on 1. I also had my com.apple.recovery.boot image on the EFI disk also.

**Comment by owaingeek** [comment]
Hi, 
Is there an update with this? Thanks

**Comment by Qonfused** [comment]
Sorry, I had meant to follow up sooner.

What does your EFI disk look like? If you created it manually, I'd make sure that there exists an EFI folder on that disk so that the root has both directories:
```
com.apple.recovery.boot/
EFI/
```

**Comment by owaingeek** [comment]
Hi,
EFI does exist. I used the already created one on the GitHub.

**Comment by Qonfused** [comment]
I'd try cloning this repository and running the build script with `.\scripts/build.ps1`. This uses a much more modern configuration than the v0.1.0 release (from February) and should better help with debugging.

It'll create a dist/ directory where you can also run the create-virtual-machine.ps1 script from:

```powershell
# Build the repository
.\scripts\build.ps1

# Use the latest version of macOS (cpu=2 cores, ram=8 GB, size=50 GB)
$ .\dist\Scripts\create-virtual-machine.ps1 -name "My New Virtual Machine"
```

**Comment by owaingeek** [comment]
I’ll try again soon. I was having issues with this previously. 
I will get back to you as soon as possible.

**Comment by Qonfused** [comment]
The README before wasn't quite correct syntactically for running those scripts (a huge oversight on my part). It was previously missing the `.\` at the start which wouldn't be runnable if you tried copy/pasting from it from the README.

**Comment by owaingeek** [comment]
Hi, this is as far as I am getting now. Still flashing on and off the screen but it says this 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/be5e839d-6fd8-4577-b8f6-2a675fd72ba8">

**Comment by owaingeek** [comment]
Let me grab a better screenshot. 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/6cb58ed5-4ff5-4a08-b5c7-58fb45e90248">

**Comment by Qonfused** [comment]
What CPU are you using and macOS version are you trying to boot?

If you're using a DEBUG build of the project (which it should by default), you should see an OpenCore log if you mount the EFI virtual disk. I'd upload it here just to verify that OpenCore isn't trying to boot into something else.

It's also possible one of the drivers (under EFI/OC/Drivers) can't run on your CPU. For older CPUs (that don't support RDRAND, i.e. Sandy Bridge and older), you'll need to use `HfsPlusLegacy` instead of `HfsPlus` (also refer to https://github.com/Qonfused/OSX-Hyper-V/issues/7#issue-2240654974 if booting a legacy macOS version). If that's the case you just change this line to `HfsPlusLegacy` and create a new virtual machine from the new build:
https://github.com/Qonfused/OSX-Hyper-V/blob/f0e99b5695b1bd6ae571e79c1bccaa4d623fabfb/src/build.yml#L11-L12

**Comment by owaingeek** [comment]
It's an Ivy-Bridge CPU, I will try that now.

**Comment by owaingeek** [comment]
That worked, this is now as far as I get now 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/1b7d3f1c-e214-4656-b4fc-f7182a15d960">
