### ISSUE TITLE
Scripts are not packaged with releases?

### ISSUE THREAD

**Issue by rcpd-alt** [Qonfused/OSX-Hyper-V#25]
First time using this project so forgive me if I'm missing fundamental but the dist contents are not actually packaged in the latest releases no? I just opted for the local build option instead and this was fine so not a big deal just a bit confusing.

**Comment by Qonfused** [comment]
Releases reflect the same output as in the `dist/` folder produced from a local build. The current configuration is newer than the v0.1.0 release which is the only major difference.

**Comment by Qonfused** [comment]
Ah I see, this is a good find! It was compressed into a tar archive with `tar -czf` but was uploaded as **.zip** instead of **.tar.gz**. Any archive reader that doesn't verify file metadata will likely be confused trying to read it.

I'll upload an updated release for v0.2.0 that should fix this issue.
