### ISSUE TITLE
Trouble Building

### ISSUE THREAD

**Issue by Lunascaped** [Qonfused/OSX-Hyper-V#3]
Whenever i attempt to build using WSL, the script tries to delete "OSX-Hyper-V/dist/scripts/bin", which doesn't exist. It then tries to execute "./scripts/lib/oce-build/scripts/patch-serial.sh" and fails due a permission error. 

I am running "bash scripts/build.sh", I have tried with sudo and without. I am using WSL2 Ubuntu (5.15.146.1-microsoft-standard-WSL2) on Windows 10.

```
root@Luna:/mnt/c/users/luna/documents/OSX-Hyper-V# bash scripts/build.sh
rm: cannot remove '/mnt/c/users/luna/documents/OSX-Hyper-V/dist/scripts/bin': No such file or directory
./scripts/lib/oce-build/scripts/patch-serial.sh: line 45: /mnt/c/users/luna/documents/OSX-Hyper-V/dist/scripts/macserial/macserial: Permission denied
md5sum: 29157: No such file or directory
 Please verify that the generated serial number is invalid by copying it into
 the Apple Check Coverage page: https://checkcoverage.apple.com/.

 Your generated serial number is shown below:



 You'll want to see an error along the lines of below:

   We're sorry, we're unable to check coverage for this serial number.

 If you see a 'valid purchase date' or 'purchase date not validated' error
 instead, you'll need to re-run this script to generate a new serial number
 and repeat this process.
```

**Comment by Qonfused** [comment]
Not entirely sure what the cause of this issue is, though this appears to fail after the main build process is finished.

The `dist/scripts/bin` directory being removed is a temporary directory for extracting executables. This is cleaned up along with a few other directories (which it appears to do successfully). This behavior is odd but safe to ignore for now.

The permission error is caused from the 'patch-serial' script trying to call `macserial` without the executable permissions set. You'll want to double check that the macserial folder exists under the `dist/scripts` directory:
- `ls ./dist/scripts/macserial/macserial`

If it exists, you may need to manually set executable permissions and re-run the patch-serial script:
- `chmod +x dist/scripts/macserial/macserial`
- `bash scripts/lib/oce-build/scripts/patch-serial.sh`

Otherwise, there isn't anything actionable in the main build process, though you can always check if there are any errors logged with `bash scripts/test.sh`.

**Comment by Lunascaped** [comment]
Yeah I tried patching mac serial with +x and it just exited with no output after. I'm not home at the moment so I'll try again and tell you the output.

**Comment by Qonfused** [comment]
The `dist/scripts/bin` folder is being disposed of earlier in the build process, which isn't affecting the build (thankfully) but is affecting cleanup.

> The `dist/scripts/bin` directory being removed is a temporary directory for extracting executables. This is cleaned up along with a few other directories (which it appears to do successfully). This behavior is odd but safe to ignore for now.

For now, you can comment out the last line of the `build.sh` script under `scripts/lib/oce-build`:

```diff
scripts/lib/oce-build/build.sh

  351 | ################################################################################
  352 | #                                 Post-build                                   #
  353 | ################################################################################
  354 | 
  355 | # Cleanup temp resources folder
  356 | rm -r "$BUILD_DIR"/.temp
  357 | rm -r "$BUILD_DIR"/.patches
+ 358 | rm -r "${SCR_DIR:?}"/bin
- 358 | # rm -r "${SCR_DIR:?}"/bin
```

**Comment by Qonfused** [comment]
There is also a new build system being worked on in #4 that may be better to use in case of any other issues.
